apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sports
  name: sports
spec:
  selector:
    matchLabels:
      app: sports
  replicas: 2
  template:
    metadata:
      labels:
        app: sports
    spec:
      containers:
      - image: ratheeshlalukms/sports:$(Build.BuildId)
        name: sports
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: sports-service
spec:
  selector:
    app: sports
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
#   nodePort: 31000
